
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
install:
  - cmd: npm install -g npm@6.9.0
  - ps: Install-Product node 12
version: build{build}
image: Visual Studio 2019
clone_folder: C:\CKli-World\CK-Core-Projects\json-graph-serializer
branches:
  only:
    - master
    - develop
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
artifacts:
  - path: '**\*.log'
    name: Log file
  - path: '**\*.trx'
    name: Visual studio test results file
  - path: '**\Tests\**\TestResult*.xml'
    name: NUnit tests result files
  - path: '**Tests\**\Logs\**\*'
    name: Log files
