
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
  - cmd: npm install -g npm@6.9.0
version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\CK-Core-Projects\json-graph-serializer
branches:
  only:
    - master
    - develop
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
